-- ===========================================================
-- Digital Library Braga — schema DB completo
-- ===========================================================
-- Riproduce da zero la struttura del catalogo su un progetto
-- Supabase nuovo. Equivalente alle 3 migration applicate via MCP:
--   20260528192435_create_catalogo_table
--   20260528201847_indice_trigram_ingresso
--   20260528223407_funzione_statistiche_catalogo
--
-- Uso: Supabase Dashboard → SQL Editor → incolla & esegui.
-- ===========================================================

-- 1) Estensioni
CREATE EXTENSION IF NOT EXISTS pg_trgm  WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA extensions;

-- 2) Trigger updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- 3) Tabella catalogo
CREATE TABLE IF NOT EXISTS public.catalogo (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 9 campi dal registro originale
  ingresso                    TEXT        NOT NULL UNIQUE,
  ingresso_num                NUMERIC GENERATED ALWAYS AS (
                                CASE
                                  WHEN ingresso ~ '^-?[0-9]+(\.[0-9]+)?$'
                                  THEN ingresso::numeric
                                  ELSE NULL
                                END
                              ) STORED,
  autore                      TEXT,
  titolo                      TEXT,
  specifica                   TEXT,
  partitura_parti_formato     TEXT,
  antica_collocazione         TEXT,
  casa_editrice               TEXT,
  anno                        TEXT,
  anno_num                    SMALLINT GENERATED ALWAYS AS (
                                NULLIF(substring(anno from '(\d{4})'), '')::smallint
                              ) STORED,
  pagine                      TEXT,

  -- 3 campi FUTURI (popolati al re-import successivo)
  data_ingresso               DATE,
  revisore                    TEXT,
  provenienza                 TEXT,

  -- Campo TECNICO: TODO integrazione futura ESP32 pick-to-light
  posizione_led               TEXT,

  -- Qualità dati / annotazioni bibliotecario
  note                        TEXT,
  da_verificare               BOOLEAN NOT NULL DEFAULT false,

  -- Timestamps
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.catalogo                          IS 'Catalogo fondo storico Biblioteca Conservatorio "G. Braga" Teramo';
COMMENT ON COLUMN public.catalogo.ingresso                 IS 'Numero d''ingresso dal registro cartaceo. TEXT per gestire valori come "4274.5" (volume bis).';
COMMENT ON COLUMN public.catalogo.ingresso_num             IS 'Parse numerico di ingresso per ordinamento; NULL se non parsable.';
COMMENT ON COLUMN public.catalogo.anno                     IS 'Anno di stampa, fedele al cartaceo. Può contenere "[s.d.]", "1900?", "1984-85".';
COMMENT ON COLUMN public.catalogo.anno_num                 IS 'Primo gruppo di 4 cifre estratto da anno, per filtri range.';
COMMENT ON COLUMN public.catalogo.partitura_parti_formato  IS 'Descrizione tipo edizione (es. "partitura", "parti di pf. e vl.") o numero di volumi (es. "1","2").';
COMMENT ON COLUMN public.catalogo.posizione_led            IS 'TODO ESP32: posizione LED sullo scaffale fisico per integrazione pick-to-light.';
COMMENT ON COLUMN public.catalogo.note                     IS 'Annotazioni libere del bibliotecario. NON viene toccato dal re-import Excel.';
COMMENT ON COLUMN public.catalogo.da_verificare            IS 'Flag per record con sospetti errori di trascrizione OCR/Gemini. NON viene toccato dal re-import.';

-- 4) Trigger updated_at
DROP TRIGGER IF EXISTS catalogo_set_updated_at ON public.catalogo;
CREATE TRIGGER catalogo_set_updated_at
BEFORE UPDATE ON public.catalogo
FOR EACH ROW
EXECUTE FUNCTION public.set_updated_at();

-- 5) Indici di ricerca
CREATE INDEX IF NOT EXISTS idx_catalogo_ingresso_num
  ON public.catalogo (ingresso_num);

CREATE INDEX IF NOT EXISTS idx_catalogo_anno_num
  ON public.catalogo (anno_num);

CREATE INDEX IF NOT EXISTS idx_catalogo_casa_editrice_lower
  ON public.catalogo (lower(casa_editrice));

CREATE INDEX IF NOT EXISTS idx_catalogo_collocazione_lower
  ON public.catalogo (lower(antica_collocazione));

-- GIN trigram per ricerca fuzzy/parziale case-insensitive
CREATE INDEX IF NOT EXISTS idx_catalogo_ingresso_trgm
  ON public.catalogo USING GIN (ingresso extensions.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_catalogo_autore_trgm
  ON public.catalogo USING GIN (lower(autore) extensions.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_catalogo_titolo_trgm
  ON public.catalogo USING GIN (lower(titolo) extensions.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_catalogo_casa_editrice_trgm
  ON public.catalogo USING GIN (lower(casa_editrice) extensions.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_catalogo_collocazione_trgm
  ON public.catalogo USING GIN (lower(antica_collocazione) extensions.gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_catalogo_da_verificare
  ON public.catalogo (da_verificare) WHERE da_verificare = true;

-- 6) Row Level Security
ALTER TABLE public.catalogo ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Catalogo selezionabile da anon e authenticated" ON public.catalogo;
CREATE POLICY "Catalogo selezionabile da anon e authenticated"
  ON public.catalogo
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- Scritture: solo service_role (bypassa RLS by design)

-- 7) Funzione SQL per la dashboard statistiche
CREATE OR REPLACE FUNCTION public.statistiche_catalogo()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, extensions
AS $$
  SELECT jsonb_build_object(
    'totale', (SELECT COUNT(*) FROM catalogo),
    'da_verificare', (SELECT COUNT(*) FROM catalogo WHERE da_verificare),
    'con_note', (SELECT COUNT(*) FROM catalogo WHERE note IS NOT NULL),
    'completezza', jsonb_build_object(
      'autore',                  (SELECT COUNT(*) FROM catalogo WHERE autore IS NOT NULL),
      'titolo',                  (SELECT COUNT(*) FROM catalogo WHERE titolo IS NOT NULL),
      'specifica',               (SELECT COUNT(*) FROM catalogo WHERE specifica IS NOT NULL),
      'partitura_parti_formato', (SELECT COUNT(*) FROM catalogo WHERE partitura_parti_formato IS NOT NULL),
      'antica_collocazione',     (SELECT COUNT(*) FROM catalogo WHERE antica_collocazione IS NOT NULL),
      'casa_editrice',           (SELECT COUNT(*) FROM catalogo WHERE casa_editrice IS NOT NULL),
      'anno',                    (SELECT COUNT(*) FROM catalogo WHERE anno IS NOT NULL),
      'pagine',                  (SELECT COUNT(*) FROM catalogo WHERE pagine IS NOT NULL),
      'data_ingresso',           (SELECT COUNT(*) FROM catalogo WHERE data_ingresso IS NOT NULL),
      'revisore',                (SELECT COUNT(*) FROM catalogo WHERE revisore IS NOT NULL),
      'provenienza',             (SELECT COUNT(*) FROM catalogo WHERE provenienza IS NOT NULL),
      'posizione_led',           (SELECT COUNT(*) FROM catalogo WHERE posizione_led IS NOT NULL)
    ),
    'per_secolo', (
      SELECT jsonb_object_agg(secolo, n) FROM (
        SELECT
          CASE
            WHEN anno_num BETWEEN 1500 AND 1699 THEN 'XVI-XVII'
            WHEN anno_num BETWEEN 1700 AND 1799 THEN 'XVIII'
            WHEN anno_num BETWEEN 1800 AND 1899 THEN 'XIX'
            WHEN anno_num BETWEEN 1900 AND 1999 THEN 'XX'
            WHEN anno_num >= 2000 THEN 'XXI'
            WHEN anno IS NOT NULL THEN 'Non parsabile'
            ELSE 'Assente'
          END AS secolo,
          COUNT(*) AS n
        FROM catalogo
        GROUP BY 1
      ) t
    ),
    'per_decennio', (
      SELECT jsonb_agg(jsonb_build_object('decennio', decennio, 'n', n) ORDER BY decennio) FROM (
        SELECT (anno_num / 10) * 10 AS decennio, COUNT(*) AS n
        FROM catalogo WHERE anno_num BETWEEN 1700 AND 2030
        GROUP BY 1 ORDER BY 1
      ) t
    ),
    'case_editrici_top', (
      SELECT jsonb_agg(jsonb_build_object('valore', label, 'conteggio', n) ORDER BY n DESC) FROM (
        SELECT INITCAP(LOWER(casa_editrice)) AS label, COUNT(*) AS n
        FROM catalogo WHERE casa_editrice IS NOT NULL
        GROUP BY LOWER(casa_editrice), INITCAP(LOWER(casa_editrice))
        ORDER BY n DESC LIMIT 15
      ) t
    ),
    'strumenti_top', (
      SELECT jsonb_agg(jsonb_build_object('valore', label, 'conteggio', n) ORDER BY n DESC) FROM (
        SELECT INITCAP(LOWER(specifica)) AS label, COUNT(*) AS n
        FROM catalogo WHERE specifica IS NOT NULL
        GROUP BY LOWER(specifica), INITCAP(LOWER(specifica))
        ORDER BY n DESC LIMIT 15
      ) t
    )
  );
$$;

GRANT EXECUTE ON FUNCTION public.statistiche_catalogo() TO anon, authenticated;
